### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sorcerer-com** [sorcerer-com/EMonitor#1]
- [ ] ~~ESP8266WiFiMesh~~
- [x] don't show last 24 hours but from 00:00
- [x] calculate current hour/month consumption

**suggestions**
- [X] current voltage
- [ ] current current
- [ ] coefficient for different channels

**ver.2**
- [x] ~~Arduino Nano as ADC~~ / ESP32 (wemos/lolin32)
- [x] AJAX ~~current data(only?)~~ and auto-refresh
- [x] Import/Export settings and data
- [x] Define only real used monitors
- [x] Define(determine by tariffStartHours) real tariffs
- [ ] ~~If connected to Internet (determine - maybe just if STA, not AP), use js libraries from there, else local~~
- [X] Cache-Control header used to cache libraries by the browser
- [X] Current Hour section to be in Wh (instead of kWh)
- [ ] ESP8266WiFiMesh
- [X] Voltage measuring (sensor: ZMPT101B)
- [X] When open UI auto check for diff in the browser time and device time, and show warning
- [X] When set current time in the settings - auto fix the timezone too
- [ ] ~~Add Real Time Clock module~~
- [ ] Use SCT-013-000 (instead of 030) and custom burden resistor to fit 5V arduino ADC or way to select type (30, 50...)
- [x] Add daily saving time (DST) option - add 1 hour to timeZone and tariffStartHours (auto check from device when update time)
- [ ] Setup wizard
- [ ] Monitor names hint cannot be seen in mobile version
- [ ] Some logo/name on the case cover
- [ ] Upgrade through Internet (get notification and autoupdate/download)
- [ ] Avoid initial reading errors
- [X] Way to check IP address (or access by dns) in the local wifi - use of NetBios
- [ ] Add to manual about NetBios way to access the device (not working in Android, Linux?) or just to check the IP address
- [ ] Add to manual that the device should be powered by 220V (110V?)

Burden resistors - sct-013-030 - 62 Ohm, for sct-013-000 add 18Ohm (/10.8 in code)
